# Generated by Django 2.2.9 on 2020-01-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='atk_choice',
            field=models.CharField(choices=[('', ''), ('Rock', 'Rock'), ('Scissors', 'Scissors'), ('Paper', 'Paper')], default='Rock', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='dfs_choice',
            field=models.CharField(choices=[('', ''), ('Rock', 'Rock'), ('Scissors', 'Scissors'), ('Paper', 'Paper')], default='Rock', max_length=10),
        ),
    ]
